version: "3"

services:
  db:
    image: arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=pass
    ports:
      - 8529:8529

  api-service:
    build: ./Compose_take_1
    ports:
      - 8000:8000
    depends_on:
      - db
